// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_twitter is a generated GoMock package.
package mock_twitter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// PostTweet mocks base method.
func (m *MockRepository) PostTweet(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostTweet", arg0)
}

// PostTweet indicates an expected call of PostTweet.
func (mr *MockRepositoryMockRecorder) PostTweet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTweet", reflect.TypeOf((*MockRepository)(nil).PostTweet), arg0)
}
